### ISSUE TITLE
"/**/" within strings get stripped in scope.replace()

### ISSUE THREAD

**Issue by infinnie** [dy/scope-css#4]
```js
scope.replace("#result:before{content:\"/**/\"}","$1$2")
```
Result:
```css
#result:before{content:""}
```
JSFiddle: https://jsfiddle.net/hwemn0sq/1/
